Repository vilega/O365Troubleshooters, pull requests merged in 2020-06, with the labels that each got.

#80 implemented Read-IntFromConsole
  O365Troubleshooters.psm1
Labels: enhancement

#85 U/alexandrunita/84
  ActionPlans/Start-DecodeSafeLinksURL.ps1
  O365Troubleshooters.psd1
Labels: bug

#87 U/vilega/86
  ActionPlans/Start-AzureADAuditSignInLogSearch.ps1
  O365Troubleshooters.psd1
Labels: bug

#88 Fixed tags from manifest. Space is not allowed
  O365Troubleshooters.psd1
Labels: bug

#89 disconnect azureAD and azureADPreview
  O365Troubleshooters.psm1
Labels: bug

#90 U/vilega/82
  ActionPlans/Export-ExoQuarantineMessages.ps1
  ActionPlans/Get-X500FromImceaexNdr.ps1
  O365Troubleshooters.psd1
  O365Troubleshooters.psm1
Labels: enhancement

#91 Align Export-ExoQuarantineMessage
  ActionPlans/Export-ExoQuarantineMessages.ps1
Labels: enhancement

#95 U/alexandrunita/16
  ActionPlans/Start-Office365Relay.ps1
Labels: bug, enhancement
